In [1]:
ls

auto_log.py                      data/                      README.md
auto_log_reading.ipynb           __init__.py                simulate_log.ipynb
auto_log_storage_rabbitMQ.ipynb  log_fields.json            simulate_log.py
auto_storage.py                  log_inspect.ipynb          storage/
auto_upload_rabbitMQ.ipynb       parse_log.ipynb            test_command.ipynb
chamber_log.py                   _PLD_Operation_Manual.pdf  test_command.py
command.py                       __pycache__/

In [2]:
import pandas as pd

In [3]:
ls data

chamber_log2.csv  chamber_log2_vis/  test_auto.csv  test_log.csv

In [27]:
df = pd.read_csv("data/chamber_log2.csv")

In [28]:
def process_row(row):
    today = datetime.date.today()
    row['Time'] = f"{today.isoformat()} {row['Time']}"
    for k, v in PARSE_DICT.items():
        row.update( parse_bit_field( row[k], v) )
    return row

In [30]:
row = df.iloc[0]
row = dict(row)

In [32]:
row = process_row(row)

In [33]:
list( row.keys() )

['Time',
 'TG No.',
 'TG Rotate',
 'TG Spin Speed',
 'TG-Z',
 'Mask1',
 'Mask2',
 'Substrate',
 'FocusLns',
 'MirrorPs',
 'ATN',
 'BTFvalve',
 'LaserHz',
 'LaserPuls',
 'Laser moni',
 'Laser set',
 'MissedPuls',
 'PwrMeter',
 'HT set',
 'HT moni',
 'Delta HT curr',
 'HT Temp set',
 'HT Temp moni',
 'Delta Temp',
 'MFC1 set',
 'MFC1 moni',
 'Delta MFC1',
 'MFC2 set',
 'MFC2 moni',
 'Delta MFC2',
 'MFC3 set',
 'MFC3 moni',
 'Delta MFC3',
 'MFC4 set',
 'MFC4 moni',
 'Delta MFC4',
 'MFC5 set',
 'MFC5 moni',
 'Delta MFC5',
 'Prc Pres Main',
 'Prc Pres Main2',
 'Vac Pres Main',
 'Back Pres Main',
 'Prc Pres L/L',
 'Vac Pres L/L',
 'Back Pres L/L',
 'Heat Stat',
 'DepoLaserStat',
 'Pump Stat',
 'Valve Stat1',
 'Valve Stat2',
 'Shut Stat',
 'Motor Stat',
 'Other Stat',
 'A Utility1',
 'A Utility2',
 'A Pump1',
 'A Pump2',
 'A EXT1',
 'A EXT2',
 'A Motor1',
 'A Motor2',
 'W Pross',
 'W etc',
 'Heater power supply (PS)',
 'PID Heater control',
 'Ramp rate setting',
 'ON/OFF monitor in PS',
 'Inter-locking in excimer laser',
 'HV in excimer laser',
 'Gate shutter',
 'DP1 (Main)',
 'DP2 (2nd RHEED)',
 'DP3 (L/L)',
 'TMP1 (Main)',
 'TMP2 (RHEED)',
 'TMP3 (L/L)',
 'TMP4 (2nd RHEED)',
 'MV10 (Main)',
 'MV11 (Main bypass)',
 'FV1 (Main)',
 'MV2 (RHEED)',
 'FV2 (RHEED)',
 'MV3 (L/L)',
 'FV3 (L/L)',
 'RV3 (L/L)',
 'Sample Shutter',
 'Target spin',
 'Motor free',
 'Baking',
 'Emergency shutdown',
 'Compress air',
 'TMP1 (Main) alarm',
 'TMP20 (RHEED) alarm',
 'TMP3 (L/L) alarm',
 'TMP21 (2nd RHEED) alarm',
 'DP1 (Main) Thermal',
 'DP2 (2nd RHEED) Thermal',
 'DP3 (L/L) Thermal',
 'DP1 (Main) Vac Error',
 'DP2 (2nd RHEED) Vac Error',
 'DP3 (L/L) Vac Error',
 'Break in baking temp sensor',
 'Tripped in baking heater line',
 'Door open in laser shield',
 'Heater power supply alarm',
 'Chiller (for heater) alarm',
 'Temperature sensor failure',
 'Laser fiber head failure',
 'Pyrometer error',
 'Pulse failure in sample rotation',
 'Pulse failure in TG revolution',
 'Pulse failure in TG height (Z)',
 'Pulse failure in Mask 1',
 'Step out in L-mask encoder',
 'Limit sensor in Mask 1',
 'Pulse failure in Mask 2',
 'Limit sensor in Mask 2',
 'Pulse failure in focus lens (R)',
 'Driver trouble in focus lens (R)',
 'Pulse failure in mirror (R)',
 'Driver trouble in mirror (R)',
 'Pulse failure in attenuator (R)',
 'Limit sensor in attenuator (R)',
 'Miss-shot in excimer laser',
 'Large temperature deviation',
 'Large drive-current deviation',
 'T',
 'Mask1 confliction']

In [5]:
from chamber_log import *

In [6]:
df.tail()

,Time,TG No.,TG Rotate,TG Spin Speed,TG-Z,Mask1,Mask2,Substrate,FocusLns,MirrorPs,...,A Utility1,A Utility2,A Pump1,A Pump2,A EXT1,A EXT2,A Motor1,A Motor2,W Pross,W etc
5939,5:54:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5940,5:55:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5941,5:56:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5942,5:57:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5943,5:58:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000

In [7]:
import datetime

In [8]:
# start_date = datetime.datetime.today().date()
start_date = datetime.datetime(2024, 3, 25).date()

In [9]:
start_date.isoformat()

'2024-03-25'

In [10]:
prev_meridiem = None
for i in range(len(df)):
    meridiem = df.loc[i, "Time"][-2:]
    if prev_meridiem == "PM" and meridiem == "AM":
        start_date += datetime.timedelta(days=1)
        
    df.loc[i, "Time"] = start_date.isoformat() +" "+ df.loc[i, "Time"]
        
    prev_meridiem = meridiem

In [11]:
df

,Time,TG No.,TG Rotate,TG Spin Speed,TG-Z,Mask1,Mask2,Substrate,FocusLns,MirrorPs,...,A Utility1,A Utility2,A Pump1,A Pump2,A EXT1,A EXT2,A Motor1,A Motor2,W Pross,W etc
0,2024-03-25 2:51:59 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
1,2024-03-25 2:52:59 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
2,2024-03-25 2:53:59 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
3,2024-03-25 2:55:00 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
4,2024-03-25 2:56:00 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5939,2024-03-29 5:54:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5940,2024-03-29 5:55:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5941,2024-03-29 5:56:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5942,2024-03-29 5:57:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000
5943,2024-03-29 5:58:10 PM,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,0x0000,0x0000,0x0000,0x0004,0x0000,0x0000,0x0000,0x0000,0x0000,0x0000

In [12]:
list( df.keys() )

['Time',
 'TG No.',
 'TG Rotate',
 'TG Spin Speed',
 'TG-Z',
 'Mask1',
 'Mask2',
 'Substrate',
 'FocusLns',
 'MirrorPs',
 'ATN',
 'BTFvalve',
 'LaserHz',
 'LaserPuls',
 'Laser moni',
 'Laser set',
 'MissedPuls',
 'PwrMeter',
 'HT set',
 'HT moni',
 'Delta HT curr',
 'HT Temp set',
 'HT Temp moni',
 'Delta Temp',
 'MFC1 set',
 'MFC1 moni',
 'Delta MFC1',
 'MFC2 set',
 'MFC2 moni',
 'Delta MFC2',
 'MFC3 set',
 'MFC3 moni',
 'Delta MFC3',
 'MFC4 set',
 'MFC4 moni',
 'Delta MFC4',
 'MFC5 set',
 'MFC5 moni',
 'Delta MFC5',
 'Prc Pres Main',
 'Prc Pres Main2',
 'Vac Pres Main',
 'Back Pres Main',
 'Prc Pres L/L',
 'Vac Pres L/L',
 'Back Pres L/L',
 'Heat Stat',
 'DepoLaserStat',
 'Pump Stat',
 'Valve Stat1',
 'Valve Stat2',
 'Shut Stat',
 'Motor Stat',
 'Other Stat',
 'A Utility1',
 'A Utility2',
 'A Pump1',
 'A Pump2',
 'A EXT1',
 'A EXT2',
 'A Motor1',
 'A Motor2',
 'W Pross',
 'W etc']

In [13]:
# expanded_df

In [14]:
for k, v in PARSE_DICT.items():
    values = df[k].values
    expanded = list(map( lambda x: parse_bit_field(x, v), values ) )
    expanded_df = pd.DataFrame(expanded)

    df = pd.concat( (df, expanded_df ), axis=1 )

In [15]:
PARSE_DICT

{'Heat Stat': {0: 'Heater power supply (PS)',
  1: 'PID Heater control',
  2: 'Ramp rate setting',
  3: 'ON/OFF monitor in PS'},
 'DepoLaserStat': {0: 'Inter-locking in excimer laser',
  1: 'HV in excimer laser',
  2: 'Gate shutter'},
 'Pump Stat': {0: 'DP1 (Main)',
  1: 'DP2 (2nd RHEED)',
  2: 'DP3 (L/L)',
  3: 'TMP1 (Main)',
  4: 'TMP2 (RHEED)',
  5: 'TMP3 (L/L)',
  6: 'TMP4 (2nd RHEED)'},
 'Valve Stat1': {0: 'MV10 (Main)',
  1: 'MV11 (Main bypass)',
  2: 'FV1 (Main)',
  3: 'MV2 (RHEED)',
  4: 'FV2 (RHEED)',
  5: 'MV3 (L/L)',
  6: 'FV3 (L/L)',
  7: 'RV3 (L/L)'},
 'Shut Stat': {0: 'Sample Shutter'},
 'Motor Stat': {0: 'Target spin', 1: 'Motor free'},
 'Other Stat': {0: 'Baking'},
 'A Utility1': {0: 'Emergency shutdown', 1: 'Compress air'},
 'A Pump1': {0: 'TMP1 (Main) alarm',
  1: 'TMP20 (RHEED) alarm',
  2: 'TMP3 (L/L) alarm',
  3: 'TMP21 (2nd RHEED) alarm',
  8: 'DP1 (Main) Thermal',
  9: 'DP2 (2nd RHEED) Thermal',
  10: 'DP3 (L/L) Thermal',
  11: 'DP1 (Main) Vac Error',
  12: 'DP2 (2nd RHEED) Vac Error',
  13: 'DP3 (L/L) Vac Error'},
 'A Pump2': {8: 'Break in baking temp sensor',
  9: 'Tripped in baking heater line'},
 'A EXT1': {1: 'Door open in laser shield',
  8: 'Heater power supply alarm',
  9: 'Chiller (for heater) alarm',
  10: 'Temperature sensor failure',
  11: 'Laser fiber head failure',
  12: 'Pyrometer error'},
 'A Motor1': {0: 'Pulse failure in sample rotation',
  4: 'Pulse failure in TG revolution',
  5: 'Pulse failure in TG height (Z)',
  8: 'Pulse failure in Mask 1',
  9: 'Step out in L-mask encoder',
  10: 'Limit sensor in Mask 1',
  11: 'Pulse failure in Mask 2',
  12: 'Limit sensor in Mask 2'},
 'A Motor2': {0: 'Pulse failure in focus lens (R)',
  1: 'Driver trouble in focus lens (R)',
  2: 'Pulse failure in mirror (R)',
  3: 'Driver trouble in mirror (R)',
  4: 'Pulse failure in attenuator (R)',
  5: 'Limit sensor in attenuator (R)'},
 'W Pross': {0: 'Miss-shot in excimer laser',
  1: 'Large temperature deviation',
  2: 'Large drive-current deviation'},
 'W etc': {0: 'T', 1: 'Mask1 confliction'}}

In [16]:
import matplotlib.pyplot as plt

In [17]:
df['Time']

0       2024-03-25 2:51:59 PM
1       2024-03-25 2:52:59 PM
2       2024-03-25 2:53:59 PM
3       2024-03-25 2:55:00 PM
4       2024-03-25 2:56:00 PM
                ...
5939    2024-03-29 5:54:10 PM
5940    2024-03-29 5:55:10 PM
5941    2024-03-29 5:56:10 PM
5942    2024-03-29 5:57:10 PM
5943    2024-03-29 5:58:10 PM
Name: Time, Length: 5944, dtype: object

In [18]:
df['Time'] = pd.to_datetime(df['Time'], format="%Y-%m-%d %I:%M:%S %p")

In [19]:
df['Time'].iloc[::100]

0      2024-03-25 14:51:59
100    2024-03-25 16:32:07
200    2024-03-25 18:12:09
300    2024-03-25 19:52:13
400    2024-03-25 21:32:15
500    2024-03-25 23:12:18
600    2024-03-26 00:52:21
700    2024-03-26 02:32:24
800    2024-03-26 04:12:26
900    2024-03-26 05:52:29
1000   2024-03-26 07:32:31
1100   2024-03-26 09:12:34
1200   2024-03-26 10:52:37
1300   2024-03-26 12:32:39
1400   2024-03-26 14:12:42
1500   2024-03-26 15:52:46
1600   2024-03-26 17:32:48
1700   2024-03-26 19:12:51
1800   2024-03-26 20:52:54
1900   2024-03-26 22:32:56
2000   2024-03-27 00:13:15
2100   2024-03-27 01:53:18
2200   2024-03-27 03:33:21
2300   2024-03-27 05:13:23
2400   2024-03-27 06:53:27
2500   2024-03-27 08:33:29
2600   2024-03-27 10:13:33
2700   2024-03-27 11:53:36
2800   2024-03-27 13:33:38
2900   2024-03-27 15:13:41
3000   2024-03-27 16:53:44
3100   2024-03-27 18:33:46
3200   2024-03-27 20:13:49
3300   2024-03-27 21:53:51
3400   2024-03-27 23:33:54
3500   2024-03-28 01:13:57
3600   2024-03-28 02:53:59
3700   2024-03-28 04:34:02
3800   2024-03-28 06:14:05
3900   2024-03-28 07:54:07
4000   2024-03-28 09:34:10
4100   2024-03-28 11:14:13
4200   2024-03-28 12:54:15
4300   2024-03-28 14:34:18
4400   2024-03-28 16:14:22
4500   2024-03-28 17:54:24
4600   2024-03-28 19:34:27
4700   2024-03-28 21:14:29
4800   2024-03-28 22:54:32
4900   2024-03-29 00:34:41
5000   2024-03-29 02:14:44
5100   2024-03-29 03:54:47
5200   2024-03-29 05:34:50
5300   2024-03-29 07:14:52
5400   2024-03-29 08:54:55
5500   2024-03-29 10:34:58
5600   2024-03-29 12:15:00
5700   2024-03-29 13:55:04
5800   2024-03-29 15:35:06
5900   2024-03-29 17:15:09
Name: Time, dtype: datetime64[ns]

In [20]:
import matplotlib

In [21]:
for c in df.columns[1:]:
    fig, ax= plt.subplots()
    # df.plot(x="Time", y="TG Rotate")
    ax.plot(df['Time'].values, df[c].values)

    ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter('%Y-%m-%d %H:%M:%S'))    
    ax.set_title(c)
    fig.autofmt_xdate()
    # break
    name = c.replace("/", "-")
    fig.savefig(f"data/chamber_log2_vis/{name}.png")
    plt.close(fig)

In [22]:
df

,Time,TG No.,TG Rotate,TG Spin Speed,TG-Z,Mask1,Mask2,Substrate,FocusLns,MirrorPs,...,Driver trouble in focus lens (R),Pulse failure in mirror (R),Driver trouble in mirror (R),Pulse failure in attenuator (R),Limit sensor in attenuator (R),Miss-shot in excimer laser,Large temperature deviation,Large drive-current deviation,T,Mask1 confliction
0,2024-03-25 14:51:59,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
1,2024-03-25 14:52:59,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
2,2024-03-25 14:53:59,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
3,2024-03-25 14:55:00,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
4,2024-03-25 14:56:00,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5939,2024-03-29 17:54:10,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
5940,2024-03-29 17:55:10,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
5941,2024-03-29 17:56:10,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
5942,2024-03-29 17:57:10,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False
5943,2024-03-29 17:58:10,1,51.5,0,0.0,0.0,0.0,261.6,100.0,-1.0,...,False,False,False,False,False,False,False,False,False,False